#! /bin/sh

sxhkd &

# turn on polybar
polybar top &

# set caps to escape
setxkbmap -option caps:escape

# make the 'X' cursor use the regular cursor shape
xsetroot -cursor_name left_ptr

# Start redshift
redshift &

# Start whatpulse
whatpulse --closedwindow --delaystartup &

# start the compton service
compton -b

# use feh to set background
feh --bg-fill $HOME/.config/backgrounds/abstract-mosaic-background.png

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Whatpulse state=floating

# Set rules for steam
bspc rule -a Steam desktop='^3'
bspc rule -a Friends desktop='3'
