#! /bin/sh

sxhkd &

# use feh to set background
feh --bg-fill $HOME/.config/backgrounds/Term.jpg

# Tray settings
# start tint2, volume controller, and whatpulse
tint2 &
volumeicon&
whatpulse --closedwindow --delaystartup &

# set caps to ctrl and escape if xcape is installed
if which xcape > /dev/null; then
	setxkbmap -option caps:ctrl_modifier
	xcape -e 'Caps_Lock=Escape' -t 200
fi

# Make pressing both shift keys turn on caps lock
setxkbmap -option shift:both_capslock_cancel

# make the 'X' cursor use the regular cursor shape
xsetroot -cursor_name left_ptr

# Use unclutter to hide the cursor when it is not necessary
unclutter &

# Start redshift after making sure it isn't running
killall -q redshift
redshift &

# start the compton service
compton -b

# start dnsmasq
dnsmasq &

# start udiskie to mount devices
udiskie -a &

# bspwm config
bspc monitor -d Term Irc Media Game Scratch

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

# bspwm colors
bspc config presel_feedback_color \#4b4b4b

# bspwm window rules
bspc rule -a Screenkey manage=off
bspc rule -a Whatpulse state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Steam desktop='^4'
bspc rule -a Friends desktop='4'
bspc rule -a Zathura state=tiled
