#!/bin/sh

# Define location of rescreen as $rescreen variable so i3 will start correctly
rescreen=~/.scripts/rescreen

# Kill the old scratchpad and then execute termite reattached to the currently running screen session
pkill -f "termite -e $rescreen --name dropdown"; termite -e ~/.scripts/rescreen --name dropdown
