#!/bin/sh

# Set id of wacom stylus to $PEN
PEN=$(xsetwacom --list devices| grep STYLUS| awk -F: '{print $2}'| awk -F' ' '{print $1}')

# Set the usable area and turn off touch
xsetwacom --set $PEN area 2730 1890 7440 4445 
xsetwacom --set $PEN touch off
