#!/bin/sh

# Set id of wacom stylus to $PEN
PEN=$(xsetwacom --list devices| grep STYLUS| awk -F: '{print $2}'| awk -F' ' '{print $1}')

# Set the usable area and turn off touch
xsetwacom --set $PEN area 2330 1490 7840 4845
xsetwacom --set $PEN touch off
